
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YO5USgxJUKbTGCB_g5XKL-gke3ilYYzl
"""

!pip install -q qiskit qiskit-algorithms qiskit-nature pyscf



pip install pylatexenc

!pip -q install py3Dmol


!pip -q install ase

)
!pip -q install gpaw gpaw-data


!pip -q install nglview py3Dmol matplotlib plotly


!pip -q install scipy numpy pandas


!pip -q install pymatgen mp-api




!pip -q install ase gpaw gpaw-data pymatgen mp-api nglview matplotlib
#LiC6 starts from here
import matplotlib.pyplot as plt

from mp_api.client import MPRester
from ase.visualize.plot import plot_atoms
from ase.io import read

from gpaw import GPAW, PW



API_KEY = "4QseSmzHkpBY2f2XBVGPYxLwDh7jM9Go"



with MPRester(API_KEY) as mpr:

    docs = mpr.materials.summary.search(
        formula="LiC6"
    )

    doc = docs[0]

    print("\n=========== STABILITY ===========")

    print("Material ID:", doc.material_id)

    print("Formula:", doc.formula_pretty)

    print("Formation Energy per Atom:",
          doc.formation_energy_per_atom,
          "eV/atom")

    print("Energy Above Hull:",
          doc.energy_above_hull,
          "eV/atom")

    if doc.energy_above_hull == 0:
        print("Status : Thermodynamically Stable")
    elif doc.energy_above_hull < 0.05:
        print("Status : Nearly Stable")
    else:
        print("Status : Metastable")

    print("===============================")

    structure = mpr.get_structure_by_material_id(doc.material_id)

structure.to("LiC6.cif")

print("Downloaded LiC6 structure.")



atoms = read("LiC6.cif")

print(atoms)



fig, ax = plt.subplots(figsize=(8,8))

plot_atoms(
    atoms,
    ax,
    rotation=('45x,35y')
)

plt.title("LiC6 Crystal Structure")

plt.show()



calc = GPAW(
    mode=PW(250),     
    xc="PBE",
    kpts=(2,2,2),     
    txt="gpaw_output.txt"
)

atoms.calc = calc

energy = atoms.get_potential_energy()

print("\n===================================")
print("Ground State Energy")
print(energy,"eV")
print("===================================")



energies, values = calc.get_dos(npts=400)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(energies, values)
plt.xlabel("Energy (eV)")
plt.ylabel("DOS")
plt.title("Density of States")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    energies,
    values
)

plt.xlabel("Energy (eV)")
plt.ylabel("Density of States")

plt.title("LiC6 Density of States")

plt.grid()

plt.show()



density = calc.get_all_electron_density()

plt.figure(figsize=(7,6))

plt.imshow(
    density[:,:,density.shape[2]//2],
    cmap="viridis"
)

plt.colorbar()

plt.title("Electron Density Slice")

plt.show()


print("\n=========== SUMMARY ===========")

print("Material :", doc.formula_pretty)

print("Ground State Energy :", energy, "eV")

print("Formation Energy :", doc.formation_energy_per_atom, "eV/atom")

print("Energy Above Hull :", doc.energy_above_hull, "eV/atom")

if doc.energy_above_hull == 0:
    print("Thermodynamically Stable")
elif doc.energy_above_hull < 0.05:
    print("Nearly Stable")
else:
    print("Metastable")

print("===============================")


!pip -q install ase gpaw gpaw-data pymatgen mp-api nglview matplotlib

import matplotlib.pyplot as plt

from mp_api.client import MPRester
from ase.visualize.plot import plot_atoms
from ase.io import read

from gpaw import GPAW, PW

#LiAl starts from here

API_KEY = "4QseSmzHkpBY2f2XBVGPYxLwDh7jM9Go"



with MPRester(API_KEY) as mpr:

    docs = mpr.materials.summary.search(
        formula="LiAl"
    )

    doc = docs[0]

    print("\n=========== STABILITY ===========")

    print("Material ID:", doc.material_id)

    print("Formula:", doc.formula_pretty)

    print("Formation Energy per Atom:",
          doc.formation_energy_per_atom,
          "eV/atom")

    print("Energy Above Hull:",
          doc.energy_above_hull,
          "eV/atom")

    if doc.energy_above_hull == 0:
        print("Status : Thermodynamically Stable")
    elif doc.energy_above_hull < 0.05:
        print("Status : Nearly Stable")
    else:
        print("Status : Metastable")

    print("===============================")

    structure = mpr.get_structure_by_material_id(doc.material_id)

structure.to("LiAl.cif")

print("Downloaded LiAl structure.")



atoms = read("LiAl.cif")

print(atoms)



fig, ax = plt.subplots(figsize=(8,8))

plot_atoms(
    atoms,
    ax,
    rotation=('45x,35y')
)

plt.title("LiAl Crystal Structure")

plt.show()



calc = GPAW(
    mode=PW(250),     # lower cutoff
    xc="PBE",
    kpts=(2,2,2),     # fewer k-points
    txt="gpaw_output.txt"
)

atoms.calc = calc

energy = atoms.get_potential_energy()

print("\n===================================")
print("Ground State Energy")
print(energy,"eV")
print("===================================")



energies, values = calc.get_dos(npts=400)

plt.figure(figsize=(8,5))
plt.plot(energies, values)
plt.xlabel("Energy (eV)")
plt.ylabel("DOS")
plt.title("Density of States")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    energies,
    values
)

plt.xlabel("Energy (eV)")
plt.ylabel("Density of States")

plt.title("LiAl Density of States")

plt.grid()

plt.show()


density = calc.get_all_electron_density()

plt.figure(figsize=(7,6))

plt.imshow(
    density[:,:,density.shape[2]//2],
    cmap="viridis"
)

plt.colorbar()

plt.title("Electron Density Slice")

plt.show()



print("\n=========== SUMMARY ===========")

print("Material :", doc.formula_pretty)

print("Ground State Energy :", energy, "eV")

print("Formation Energy :", doc.formation_energy_per_atom, "eV/atom")

print("Energy Above Hull :", doc.energy_above_hull, "eV/atom")

if doc.energy_above_hull == 0:
    print("Thermodynamically Stable")
elif doc.energy_above_hull < 0.05:
    print("Nearly Stable")
else:
    print("Metastable")

print("===============================")
